version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - COUCHDB_URL=http://couchdb:5984
  #     - COUCHDB_USERNAME=${COUCHDB_USERNAME}
  #     - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
  #     - COUCHDB_DATABASE=${COUCHDB_DATABASE}
  #   depends_on:
  #     - couchdb

  couchdb:
    image: couchdb:3.3.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data: 